hanye:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hanye_take_out
#    username: root
#    password: 20040111
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: xinni_self_ordering
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx869b8876e83b4ca4
    secret: 623902844aefc6084df37d34c12f8bf5
    # 别人的文件，由于没企业商户号，这里只是摆设
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://9ea0754.r19.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://9ea0754.r19.cpolar.top/notify/refundSuccess
  deepseek:
    api-key: 3zPnktNdg3tHQpAvGyrkU1KtQGFLn6OkJDc5ZZt_vH9I4uAV9Hv859ouCB5WDUZh5SihK-rwi_f6cjYDeU-6jA
    api-url: https://maas-cn-southwest-2.modelarts-maas.com/v1/infers/271c9332-4aa6-4ff5-95b3-0cf8bd94c394/v1/chat/completions
    model: DeepSeek-V3
    timeout: 30000
